In [4]:
import torch

In [7]:
a = torch.arange(0, 5, dtype=torch.float).unsqueeze(1)
print(a)
b = torch.arange(0, 5, dtype=torch.float).unsqueeze(0)
print(b)
C = torch.arange(0, 5, dtype=torch.float)
print(C)
print(a.shape)
print(b.shape)
print(C.shape)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])
tensor([[0., 1., 2., 3., 4.]])
tensor([0., 1., 2., 3., 4.])
torch.Size([5, 1])
torch.Size([1, 5])
torch.Size([5])
